# Generated by Django 3.1.4 on 2020-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=16, unique=True)),
                ('update_time', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
